/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoConstants.java */
package controladoras;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorSintacticoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int NUMBER = 7;
  /** RegularExpression Id. */
  int BEGIN = 8;
  /** RegularExpression Id. */
  int END = 9;
  /** RegularExpression Id. */
  int IF = 10;
  /** RegularExpression Id. */
  int THEN = 11;
  /** RegularExpression Id. */
  int ELSE = 12;
  /** RegularExpression Id. */
  int BOLEANO = 13;
  /** RegularExpression Id. */
  int NOT = 14;
  /** RegularExpression Id. */
  int OPERADORR = 15;
  /** RegularExpression Id. */
  int OPERADORL = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int PARENTESISABIERTO = 18;
  /** RegularExpression Id. */
  int DO = 19;
  /** RegularExpression Id. */
  int PARENTESISCERRADO = 20;
  /** RegularExpression Id. */
  int ASIGNACION = 21;
  /** RegularExpression Id. */
  int TO = 22;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 23;
  /** RegularExpression Id. */
  int DOUBLECOMMA = 24;
  /** RegularExpression Id. */
  int CADENA = 25;
  /** RegularExpression Id. */
  int OPERADOR = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"+\"",
    "<NUMBER>",
    "\"begin\"",
    "\"end\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "<BOLEANO>",
    "\"not\"",
    "<OPERADORR>",
    "<OPERADORL>",
    "\"while\"",
    "\"(\"",
    "\"do\"",
    "\")\"",
    "\"<-\"",
    "\"to\"",
    "<IDENTIFICADOR>",
    "\"\\\"\"",
    "<CADENA>",
    "<OPERADOR>",
  };

}
