/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoConstants.java */
package controladoras;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorSintacticoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int BEGIN = 7;
  /** RegularExpression Id. */
  int END = 8;
  /** RegularExpression Id. */
  int DECLARE = 9;
  /** RegularExpression Id. */
  int ENDDECLARE = 10;
  /** RegularExpression Id. */
  int CALL = 11;
  /** RegularExpression Id. */
  int PROCEDURE = 12;
  /** RegularExpression Id. */
  int FUNCTION = 13;
  /** RegularExpression Id. */
  int RETURN = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int THEN = 16;
  /** RegularExpression Id. */
  int ELIF = 17;
  /** RegularExpression Id. */
  int ELSE = 18;
  /** RegularExpression Id. */
  int BOLEANO = 19;
  /** RegularExpression Id. */
  int TIPO = 20;
  /** RegularExpression Id. */
  int NOT = 21;
  /** RegularExpression Id. */
  int OPERADORR = 22;
  /** RegularExpression Id. */
  int OPERADORL = 23;
  /** RegularExpression Id. */
  int WHILE = 24;
  /** RegularExpression Id. */
  int FOR = 25;
  /** RegularExpression Id. */
  int REPEAT = 26;
  /** RegularExpression Id. */
  int UNTIL = 27;
  /** RegularExpression Id. */
  int STACK = 28;
  /** RegularExpression Id. */
  int QUEUE = 29;
  /** RegularExpression Id. */
  int ADD = 30;
  /** RegularExpression Id. */
  int REMOVE = 31;
  /** RegularExpression Id. */
  int PISOBAJO = 32;
  /** RegularExpression Id. */
  int PARENTESISABIERTO = 33;
  /** RegularExpression Id. */
  int PARENTESISCERRADO = 34;
  /** RegularExpression Id. */
  int CORCHETEABIERTO = 35;
  /** RegularExpression Id. */
  int CORCHETECERRADO = 36;
  /** RegularExpression Id. */
  int ASIGNACION = 37;
  /** RegularExpression Id. */
  int DO = 38;
  /** RegularExpression Id. */
  int TO = 39;
  /** RegularExpression Id. */
  int COMA = 40;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 41;
  /** RegularExpression Id. */
  int DOUBLECOMMA = 42;
  /** RegularExpression Id. */
  int CADENA = 43;
  /** RegularExpression Id. */
  int OPERADOR = 44;
  /** RegularExpression Id. */
  int LENGTH = 45;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "<NUMBER>",
    "\"begin\"",
    "\"end\"",
    "\"declare\"",
    "\"enddeclare\"",
    "\"call\"",
    "\"procedure\"",
    "\"function\"",
    "\"return\"",
    "\"if\"",
    "\"then\"",
    "\"elif\"",
    "\"else\"",
    "<BOLEANO>",
    "<TIPO>",
    "\"not\"",
    "<OPERADORR>",
    "<OPERADORL>",
    "\"while\"",
    "\"for\"",
    "\"repeat\"",
    "\"until\"",
    "\"stack\"",
    "\"queue\"",
    "\".add\"",
    "\".pop\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"<-\"",
    "\"do\"",
    "\"to\"",
    "\",\"",
    "<IDENTIFICADOR>",
    "\"\\\"\"",
    "<CADENA>",
    "<OPERADOR>",
    "\".length\"",
  };

}
