
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 12 23:17:23 COT 2016
//----------------------------------------------------

package controladoras;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 3;
  public static final int ASIGNACION = 7;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 2;
  public static final int BEGIN = 5;
  public static final int END = 6;
  public static final int EOF = 0;
  public static final int CADENA = 4;
}

